### ISSUE TITLE
Unable to run `./buckw build` due to broken symbolic link

### ISSUE THREAD

**Issue by runningcode** [uber-common/android-build-eval#5]
When running the buck build I get the following error:
```
chmod: cannot operate on dangling symlink '/Users/no/workspace/android-build-eval/mobile_app1/.okbuck/workspace/buck_binary/buck-a68ef0d834eec5fe381cb3e8e8612ba9fa42a09d.pex'
```

The pex file contains a broken symbolic link since it refers to a directory which may not exist: https://github.com/uber-common/android-build-eval/blob/master/mobile_app1/.okbuck/workspace/buck_binary/buck-a68ef0d834eec5fe381cb3e8e8612ba9fa42a09d.pex

**Comment by oliviernotteghem** [comment]
I see. I forgot one step in the README file. Please run `SKIP_OKBUCK=0 ./gradlew -Dokbuck.wrapper=true okbuck --no-configuration-cache` to re-generate OkBuck file/wrapper. After that `buckw` should work properly. Let me know how this goes.

**Comment by oliviernotteghem** [comment]
@runningcode I've retested things on a second machine and it went through. But I'll wait to hear from you before closing this issue.

**Comment by runningcode** [comment]
I ran this on the latest master `SKIP_OKBUCK=0 ./gradlew -Dokbuck.wrapper=true okbuck --no-configuration-cache` and it completed successfully.
I then ran the following and got the following error: 
```
❯ ./buckw build rootModule:src_release
Buck encountered an internal error
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.buck.util.environment.MacWifiSsidFinder
	at com.facebook.buck.util.environment.NetworkInfo.getWifiSsid(NetworkInfo.java:77)
	at com.facebook.buck.util.environment.DefaultExecutionEnvironment.getWifiSsid(DefaultExecutionEnvironment.java:79)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1176)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:476)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)

Buck encountered an internal error
java.lang.NoClassDefFoundError: Could not initialize class com.facebook.buck.util.environment.MacWifiSsidFinder
	at com.facebook.buck.util.environment.NetworkInfo.getWifiSsid(NetworkInfo.java:77)
	at com.facebook.buck.util.environment.DefaultExecutionEnvironment.getWifiSsid(DefaultExecutionEnvironment.java:79)
	at com.facebook.buck.cli.MainRunner.runMainWithExitCode(MainRunner.java:1176)
	at com.facebook.buck.cli.MainRunner.runMainThenExit(MainRunner.java:476)
	at com.facebook.buck.cli.MainWithNailgun.nailMain(MainWithNailgun.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
	at com.facebook.nailgun.NGSession.run(NGSession.java:199)
	
	
I don't think I installed buck in any way nor did I see instruction in the readme. I assume that running the buck wrapper should perform the install?

**Comment by oliviernotteghem** [comment]
@runningcode : good news and bad news. Good : issue seems fixed Bad : you're running on MacOS Catalina, where buck is not supported yet (there is an open issue on this since May 2020, at Uber we use a forked patched to workaround the crash).

Is this possible for you to use a linux box or different Macbook?

**Comment by oliviernotteghem** [comment]
https://github.com/facebook/buck/issues/2491

**Comment by oliviernotteghem** [comment]
This has been fixed!

https://github.com/uber-common/android-build-eval/commit/f60b988db680d12cc5560d4833b1aa33df1728ab
