### ISSUE TITLE
Failed to run Buck 

### ISSUE THREAD

**Issue by nkoroste** [uber-common/android-build-eval#9]
```
> Executing cleaning phase with `./buckw fetch ...`
Parsing buck files: finished in 20.2 sec
Overridden kotlin:kotlin_home path not found: buck-out/gen/.okbuck/workspace/kotlin_home/kotlin_home/kotlin_home
    When creating rule //module1259:src_main.
Unexpected exit code 1 for command `./buckw fetch ...`

* Running warm-up build #1
java.lang.RuntimeException: Could not run command ./buckw build //rootModule:src_debug in dir /home/nk/src/upstream/android-build-eval/mobile_app1/.. Exited with result 1
        at org.gradle.profiler.CommandExec$RunHandle.waitForSuccess(CommandExec.java:178)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:77)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:35)
	at org.gradle.profiler.CommandExec.run(CommandExec.java:30)
	at org.gradle.profiler.Main.lambda$runBuckScenario$5(Main.java:354)
	at org.gradle.profiler.Main.lambda$tryRunAndContinue$9(Main.java:423)
	at org.gradle.profiler.Main.tryRun(Main.java:441)
	at org.gradle.profiler.Main.tryRunAndContinue(Main.java:431)
	at org.gradle.profiler.Main.tryRunAndContinue(Main.java:422)
	at org.gradle.profiler.Main.runBuckScenario(Main.java:351)
	at org.gradle.profiler.Main.run(Main.java:76)
	at org.gradle.profiler.Main.main(Main.java:27)

```

Running on Linux

**Comment by nkoroste** [comment]
NVM, I was on an older SHA, didn't see latest fixes... trying again...

**Comment by oliviernotteghem** [comment]
Make sure OKBUCK is disabled (SKIP_OKBUCK=1), I also update README.md for up-to-date info how to run buck build.

**Comment by oliviernotteghem** [comment]
Please re-open issue if you encouter problem against with latest instructions.
